import { random } from '../utils/random';
import { biomeAt,heightAt,insideIsland,isWater,distanceToTrail } from '../world/map';
import { animalZones,worldLayout } from '../world/layout';
export type AnimalState='IDLE'|'MOVE'|'ACTION'|'PAUSE';
export function safeAnimalPoint(zone:number,x:number,z:number){const a=animalZones[zone],radius=a.species==='deer'?.55:a.species==='fox'?.35:.19;return Math.hypot(x-a.x,z-a.z)<a.r-radius&&biomeAt(x,z)===biomeAt(a.x,a.z)&&insideIsland(x,z,radius)&&!isWater(x,z)&&distanceToTrail(x,z)>radius+.48&&!worldLayout.obstacles.some(o=>o.kind!=='habitat'&&Math.hypot(x-o.x,z-o.z)<o.r+radius);}
export function safeAnimalSegment(zone:number,x:number,z:number,tx:number,tz:number){const n=Math.ceil(Math.hypot(tx-x,tz-z)/.15);for(let i=0;i<=n;i++){const t=i/Math.max(1,n);if(!safeAnimalPoint(zone,x+(tx-x)*t,z+(tz-z)*t))return false;}return true;}
export class AnimalController{state:AnimalState='IDLE';time=0;until:number;x:number;z:number;tx:number;tz:number;angle=0;hop=0;private r:()=>number;
 constructor(public zone:number,seed:number){const a=animalZones[zone];this.x=this.tx=a.x;this.z=this.tz=a.z;this.r=random(seed);this.until=1.5+this.r()*4;for(let i=0;i<24;i++){const angle=this.r()*6.283,d=this.r()*(a.r-.5),x=a.x+Math.cos(angle)*d,z=a.z+Math.sin(angle)*d;if(safeAnimalPoint(zone,x,z)){this.x=this.tx=x;this.z=this.tz=z;break;}}}
 advance(delta:number){const dt=Math.min(delta,.05),a=animalZones[this.zone];this.time+=dt;this.hop=0;if(this.state==='MOVE'){const dx=this.tx-this.x,dz=this.tz-this.z,d=Math.hypot(dx,dz),step=(a.species==='fox'?.32:a.species==='rabbit'?.42:.23)*dt;if(d<step+.01){this.x=this.tx;this.z=this.tz;this.state='PAUSE';this.until=this.time+1+this.r()*2;}else{this.x+=dx/d*step;this.z+=dz/d*step;this.angle=Math.atan2(dx,dz);if(a.species==='rabbit')this.hop=Math.max(0,Math.sin(this.time*12))*.12;}}
 else if(this.time>this.until){if(this.state==='IDLE'){this.state='ACTION';this.until=this.time+2+this.r()*4;}else{let target=false;for(let i=0;i<12;i++){const angle=this.r()*6.283,d=this.r()*Math.max(.05,a.r-(a.species==='deer'?.65:a.species==='fox'?.45:.29)),x=a.x+Math.cos(angle)*d,z=a.z+Math.sin(angle)*d;if(safeAnimalSegment(this.zone,this.x,this.z,x,z)){this.tx=x;this.tz=z;target=true;break;}}this.state=target?'MOVE':'IDLE';this.until=this.time+2+this.r()*3;}}
 if(a.species==='frog'&&this.state==='ACTION')this.hop=Math.max(0,Math.sin((this.time-this.until+2)*3))*.12;return{y:heightAt(this.x,this.z)+this.hop};}}
