import { useQuality } from '../environment/quality';
import { useEffect,useMemo,useRef } from 'react';
import { useAnimations,useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { Box3,Group,Mesh,SkinnedMesh,MeshStandardMaterial,Vector3 } from 'three';
import { clone } from 'three/examples/jsm/utils/SkeletonUtils.js';
import type { Settings } from '../environment/settings';
import { heightAt } from '../world/map';
import { AnimalController } from './behavior';
import { rabbitBody,rabbitHead,rabbitEar,foot,birdBody,fishBody,frogBody,flightWing } from './shapes';
const black='#373b32';
function Rigged({species,zone,settings,index=0}:{index?:number;species:'deer'|'fox';zone:number;settings:Settings}){const {scene,animations}=useGLTF(import.meta.env.BASE_URL+'world-assets/animals/'+species+'.glb'),ref=useRef<Group>(null!),last=useRef(''),control=useMemo(()=>new AnimalController(zone,(species==='deer'?34:98)+index*317),[zone,species,index]);const model=useMemo(()=>{const copy=clone(scene);copy.updateMatrixWorld(true);copy.traverse(o=>{if(o instanceof SkinnedMesh){o.skeleton.update();o.computeBoundingBox();}});const box=new Box3().setFromObject(copy),size=box.getSize(new Vector3()),scale=(species==='deer'?1.65:.63)/size.y;copy.scale.setScalar(scale);copy.position.y=-box.min.y*scale;copy.traverse(o=>{if(o instanceof Mesh){const materials=Array.isArray(o.material)?o.material:[o.material];const copies=materials.map(m=>{const c=m.clone() as MeshStandardMaterial;c.roughness=1;c.metalness=0;c.flatShading=true;return c;});o.material=Array.isArray(o.material)?copies:copies[0];o.castShadow=true;o.receiveShadow=true;}});return copy;},[scene,species]);const {actions,mixer}=useAnimations(animations,model);useEffect(()=>()=>model.traverse(o=>{if(o instanceof Mesh)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}),[model]);useFrame(({camera},d)=>{const distance=Math.hypot(camera.position.x-control.x,camera.position.z-control.z);mixer.timeScale=settings.paused||distance>65?0:distance>30?.35:1;if(!settings.paused&&distance<65)control.advance(d);ref.current.position.set(control.x,heightAt(control.x,control.z),control.z);ref.current.rotation.y=control.angle;const name=control.state==='MOVE'?'Walk':control.state==='ACTION'?(species==='deer'?'Eating':'Idle_2'):'Idle';if(last.current!==name){actions[last.current]?.fadeOut(.35);actions[name]?.reset().fadeIn(.35).play();last.current=name;}});return <group ref={ref} name={'wildlife-'+species} userData={{kind:'animal',zone}}><primitive object={model}/></group>;}
function Rabbit({settings,index=0}:{settings:Settings;index?:number}){const ref=useRef<Group>(null!),ears=useRef<Group>(null!),c=useMemo(()=>new AnimalController([2,8,9,10][index],194+index*71),[index]);useFrame(({camera},d)=>{if(Math.hypot(camera.position.x-c.x,camera.position.z-c.z)>65)return;if(!settings.paused)c.advance(d);ref.current.position.set(c.x,heightAt(c.x,c.z)+c.hop,c.z);ref.current.rotation.y=c.angle;ears.current.rotation.x=Math.sin(c.time*.8)*.07;});return <group ref={ref} name="wildlife-rabbit"><mesh geometry={rabbitBody} castShadow><meshStandardMaterial color="#9a8665" flatShading/></mesh><mesh geometry={rabbitHead} castShadow><meshStandardMaterial color="#aa9674" flatShading/></mesh><group ref={ears} position={[0,.53,.26]}>{[-1,1].map(side=><mesh key={side} geometry={rabbitEar} position={[side*.072,0,0]} rotation={[.08,0,side*.12]}><meshStandardMaterial color="#9c896b" flatShading/></mesh>)}</group>{[-1,1].map(side=><group key={side}><mesh geometry={foot} position={[side*.12,0,-.18]}><meshStandardMaterial color="#a18d6e" flatShading/></mesh><mesh geometry={foot} position={[side*.095,0,.16]} scale={[.7,1,.6]}><meshStandardMaterial color="#a18d6e" flatShading/></mesh><mesh position={[side*.11,.48,.36]}><icosahedronGeometry args={[.019,0]}/><meshStandardMaterial color={black}/></mesh></group>)}<mesh position={[0,.25,-.34]}><icosahedronGeometry args={[.073,1]}/><meshStandardMaterial color="#d3cdbc" flatShading/></mesh></group>;}
function Frog({settings,index=0}:{settings:Settings;index?:number}){const ref=useRef<Group>(null!),c=useMemo(()=>new AnimalController([3,11,12,13][index],831+index*163),[index]);useFrame(({camera},d)=>{if(Math.hypot(camera.position.x-c.x,camera.position.z-c.z)>65)return;if(!settings.paused)c.advance(d);ref.current.position.set(c.x,heightAt(c.x,c.z)+c.hop,c.z);ref.current.rotation.y=c.angle;});return <group ref={ref} name="wildlife-frog"><mesh geometry={frogBody}><meshStandardMaterial color="#6b9454" flatShading/></mesh>{[-1,1].map(side=><group key={side}><mesh geometry={foot} position={[side*.15,0,-.06]} scale={[1.1,1,1.3]} rotation={[0,side*.5,0]}><meshStandardMaterial color="#527c46" flatShading/></mesh><mesh position={[side*.075,.17,.11]}><icosahedronGeometry args={[.027,0]}/><meshStandardMaterial color="#273e2a"/></mesh></group>)}</group>;}
function Bird({settings,index}:{settings:Settings;index:number}){const ref=useRef<Group>(null!),left=useRef<Mesh>(null!),right=useRef<Mesh>(null!),time=useRef(index*7.13);useFrame((_,d)=>{if(!settings.paused)time.current+=Math.min(d,.05);const phase=time.current%22,flying=index>=2||phase>7&&phase<16,u=index>=2?time.current*.045+index:(phase-7)/9,x=index>=2?[-14,17,-4,12][index-2]+Math.cos(u*6.283)*3:17+index*.8+(flying?Math.sin(u*Math.PI*2)*1.9:0),z=index>=2?[-8,4,9,-9][index-2]+Math.sin(u*6.283)*2:-11.4+(flying?Math.sin(u*Math.PI)*2.1:0);ref.current.position.set(x,index>=2?heightAt(x,z)+3.2+index*.2:heightAt(17,-11)+4.49-index*.35+(flying?Math.sin(u*Math.PI)*1.5:0),z);ref.current.rotation.y=flying?u*6.283:.6;left.current.rotation.z=flying?Math.sin(time.current*17)*.65:-1.35;right.current.rotation.z=-left.current.rotation.z;});return <group ref={ref} name="wildlife-bird"><mesh geometry={birdBody}><meshStandardMaterial color="#728c9a" flatShading/></mesh><mesh ref={left} geometry={flightWing} position={[.025,.06,0]}><meshStandardMaterial color="#4e697b" side={2}/></mesh><mesh ref={right} geometry={flightWing} scale={[-1,1,1]} position={[-.025,.06,0]}><meshStandardMaterial color="#4e697b" side={2}/></mesh><mesh position={[0,.13,.25]} rotation={[Math.PI/2,0,0]}><coneGeometry args={[.029,.09,4]}/><meshStandardMaterial color="#d5bb6d"/></mesh></group>;}
function Butterfly({settings,index}:{settings:Settings;index:number}){const ref=useRef<Group>(null!),wing=useRef<Group>(null!),time=useRef(index*.83);useFrame((_,d)=>{if(!settings.paused)time.current+=Math.min(d,.05);const t=time.current*.4,x=[-16,-10,-22.8,-2.4][index%4]+Math.sin(t+index)*1.5,z=[4.8,8,8.4,5.4][index%4]+Math.cos(t*1.3+index)*1.2;ref.current.position.set(x,heightAt(x,z)+.45+Math.sin(t*2+index)*.15,z);ref.current.rotation.y=t;wing.current.rotation.z=Math.sin(time.current*19)*.6;});return <group ref={ref} scale={.28} name="wildlife-butterfly"><group ref={wing}><mesh geometry={flightWing}><meshBasicMaterial color={index%2?'#e7bb63':'#e2b4a2'} side={2}/></mesh><mesh geometry={flightWing} scale={[-1,1,1]}><meshBasicMaterial color="#db9b56" side={2}/></mesh></group></group>;}
function Fish({settings,index}:{settings:Settings;index:number}){const ref=useRef<Group>(null!),tail=useRef<Mesh>(null!),time=useRef(index*3.1);useFrame((_,d)=>{if(!settings.paused)time.current+=Math.min(d,.05);const t=time.current*.16+index,x=7+Math.cos(t)*(2.3+index%2*.4),z=5.1+Math.sin(t)*2.3;ref.current.position.set(x,.085,z);ref.current.rotation.y=Math.atan2(-Math.sin(t),Math.cos(t));tail.current.rotation.y=Math.sin(time.current*4)*.28;});return <group ref={ref} scale={[.75,.55,.75]} name="wildlife-fish"><mesh geometry={fishBody}><meshStandardMaterial color={index%2?'#c6a06b':'#587e79'} flatShading/></mesh><mesh ref={tail} geometry={flightWing} position={[0,0,-.24]} rotation={[0,0,Math.PI/2]} scale={[.32,.5,.5]}><meshStandardMaterial color="#778974" side={2}/></mesh></group>;}
export function Wildlife({settings}:{settings:Settings}){const quality=useQuality();return <group>{[0,1,2].map(i=><Rigged key={"deer"+i} index={i} species="deer" zone={[0,4,5][i]} settings={settings}/>)}{[0,1,2].map(i=><Rigged key={"fox"+i} index={i} species="fox" zone={[1,6,7][i]} settings={settings}/>)}{[0,1,2,3].map(i=><Rabbit key={"rabbit"+i} index={i} settings={settings}/>)}{[0,1,2,3].map(i=><Frog key={"frog"+i} index={i} settings={settings}/>)}{[0,1,2,3,4,5].map(i=><Bird key={i} index={i} settings={settings}/>)}{Array.from({length:Math.round(30*quality.density)},(_,i)=><Butterfly key={i} index={i} settings={settings}/>)}{Array.from({length:12},(_,i)=><Fish key={i} index={i} settings={settings}/>)}</group>;}
