import { describe,it,expect } from 'vitest';
import { CharacterController,emptyInput,canStand,groundAt,bridgeHeight,findSpawn,obstacles } from './controller';
import { bridges } from '../world/layout';
import { heightAt } from '../world/map';
describe('player navigation',()=>{
 it('clears an actual boulder in the scene while jumping, then lands',()=>{const rock=obstacles.find(o=>o.kind==='rock'&&o.height>.38&&o.height<.7&&canStand(o.x-o.r-.27,o.z)&&canStand(o.x+o.r+.27,o.z));expect(rock).toBeDefined();const o=rock!,c=new CharacterController(),i=emptyInput();c.position={x:o.x-o.r-.27,y:groundAt(o.x-o.r-.27,o.z),z:o.z};c.cameraYaw=-Math.PI/2;i.moveY=1;i.run=true;i.jump=true;let above=false;for(let n=0;n<90;n++){c.step(i,1/60);if(Math.abs(c.position.x-o.x)<o.r&&Math.abs(c.position.z-o.z)<.1&&c.position.y>=groundAt(o.x,o.z)+o.height-.08)above=true;if(c.position.x>o.x+o.r+.23)break;}expect(above).toBe(true);expect(c.position.x).toBeGreaterThan(o.x+o.r);i.moveY=0;for(let n=0;n<180;n++)c.step(i,1/60);expect(c.grounded).toBe(true);expect(c.position.y).toBeCloseTo(groundAt(c.position.x,c.position.z));});
 it('does not make tree trunks passable during an ordinary jump',()=>{const tree=obstacles.find(o=>o.kind==='tree')!;expect(canStand(tree.x,tree.z,.21,groundAt(tree.x,tree.z)+1)).toBe(false);});
 it('walks and runs from the clear spawn with the correct animation',()=>{const c=new CharacterController(),i=emptyInput();c.reset();const before={...c.position};i.moveY=1;c.step(i,1/60);expect(c.animation).toBe('Walk');const walked=Math.hypot(c.position.x-before.x,c.position.z-before.z);i.run=true;const runStart={...c.position};c.step(i,1/60);expect(c.animation).toBe('Run');expect(Math.hypot(c.position.x-runStart.x,c.position.z-runStart.z)).toBeGreaterThan(walked);});
 it('spawns on dry accessible ground',()=>{const p=findSpawn();expect(canStand(p.x,p.z)).toBe(true);expect(p.y).toBe(groundAt(p.x,p.z));});
 it('blocks the hero trunk, campfire, deep lake and island boundary',()=>{for(const [x,z] of [[17,2],[-14,8.4],[7,7],[100,100]])expect(canStand(x,z)).toBe(false);});
 it('makes every bridge center traversable above water',()=>{for(const b of bridges){expect(bridgeHeight(b.x,b.z)).toBeCloseTo(b.y+.065);expect(canStand(b.x,b.z)).toBe(true);}});
 it('lands a jump back on the sampled surface',()=>{const c=new CharacterController(),i=emptyInput();i.jump=true;c.step(i,1/60);expect(c.grounded).toBe(false);expect(c.position.y).toBeGreaterThan(groundAt(c.position.x,c.position.z));for(let j=0;j<120;j++)c.step(i,1/60);expect(c.grounded).toBe(true);expect(c.position.y).toBe(groundAt(c.position.x,c.position.z));});
 it('clamps the camera pitch and consumes camera/jump impulses',()=>{const c=new CharacterController(),i=emptyInput();i.cameraY=10000;i.cameraX=30;i.jump=true;c.step(i,.016);expect(c.cameraPitch).toBe(.85);expect(i.cameraX).toBe(0);expect(i.jump).toBe(false);});
 it('moves relative to camera heading and resets safely',()=>{const c=new CharacterController(),before={...c.position},i=emptyInput();c.cameraYaw=Math.PI/2;i.moveY=1;c.step(i,.05);expect(c.position.x).toBeLessThan(before.x);c.reset();expect(c.position).toEqual(findSpawn());expect(c.animation).toBe('Idle');});
});
