import { Component,lazy,Suspense,useEffect,useState,useRef,useCallback,type ReactNode } from 'react';
import { Canvas } from '@react-three/fiber';
import type { Destination,Season,Settings,Weather } from './environment/settings';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { PlayContext,type PlaySession } from './player/session';
import { CharacterController,emptyInput,type WorldMode } from './player/controller';
import { PlayHUD } from './player/PlayHUD';
import { useForestAudio } from './environment/forestAudio';
import { QualityContext,QualityMonitor,presets,type Quality,type Tier } from './environment/quality';
const World=lazy(()=>import('./world/World'));
class Boundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return{error:true};}render(){return this.state.error?<div className="error"><h1>The world couldn’t open</h1><p>This world needs WebGL and hardware acceleration.</p><button onClick={()=>location.reload()}>Try again</button></div>:this.props.children;}}
export default function App(){
 const [settings,setSettings]=useState<Settings>({season:'summer',weather:'clear',night:false,paused:matchMedia('(prefers-reduced-motion: reduce)').matches,destination:'overview'});
 const [mode,setMode]=useState<WorldMode>('explore'),[asset,setAsset]=useState<PlaySession['asset']>(null),[assetStatus,setAssetStatus]=useState('preparing'),[quality,setQuality]=useState<Quality>('auto'),[tier,setTier]=useState<Tier>(innerWidth<900||devicePixelRatio>2?'low':'medium');
 const [view,setView]=useState<'first'|'third'>('third'),[photo,setPhoto]=useState<string|null>(null),photoRequest=useRef(false);
 useEffect(()=>()=>{if(photo)URL.revokeObjectURL(photo);},[photo]);
 const onPhoto=useCallback((blob:Blob)=>setPhoto(URL.createObjectURL(blob)),[]);
 const controller=useRef(new CharacterController()).current,input=useRef(emptyInput()).current,loading=useRef(false);
 const ready=useCallback(()=>{if(loading.current)return;loading.current=true;setTimeout(()=>new GLTFLoader().load('./world-assets/characters/human-explorer.glb',g=>{const required=['idle','walk','run','jump'];if(!required.every(n=>g.animations.some(c=>c.name.toLowerCase()===n))){setAssetStatus('animations missing');return;}setAsset({scene:g.scene,animations:g.animations});setAssetStatus('ready');},undefined,()=>setAssetStatus('model missing')),250);},[]);
 const exit=useCallback(()=>{Object.assign(input,emptyInput());setMode(m=>m==='explore'||m==='transitioningToExplore'?m:'transitioningToExplore');},[input]);
 const finish=useCallback(()=>{setMode(m=>{if(m==='transitioningToExplore')setSettings(v=>({...v,destination:'overview'}));return m==='transitioningToPlay'?'play':m==='transitioningToExplore'?'explore':m;});},[]);
 const enter=()=>{if(!asset)return;audio.start();setMode('transitioningToPlay');const root=document.documentElement;try{const request=root.requestFullscreen?.();request?.then(()=>{if(navigator.maxTouchPoints>0){const orientation=screen.orientation as ScreenOrientation&{lock?:(s:string)=>Promise<void>};orientation.lock?.('landscape').catch(()=>{});}}).catch(()=>{});}catch{} };
 useEffect(()=>{window.parent.postMessage({type:'banori-play',active:mode!=='explore'},location.origin);if(mode==='explore'){screen.orientation?.unlock?.();if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});}},[mode]);
 useEffect(()=>{const changed=()=>{if(!document.fullscreenElement)exit();};document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed);},[exit]);
 useEffect(()=>{if(mode==='play')document.querySelector('main')?.focus();},[mode]);
 const session:PlaySession={view,setView,photoRequest,photo,onPhoto,mode,controller,input,asset,finish,ready};
 const effective=quality==='auto'?tier:quality;
 const [visible,setVisible]=useState(true);const sectionVisible=useRef(true);
 const audio=useForestAudio(settings,controller,mode!=='explore',visible);
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.origin===location.origin&&event.source===window.parent&&event.data?.type==='banori-visible'){sectionVisible.current=Boolean(event.data.visible);setVisible(sectionVisible.current&&!document.hidden);}};const visibility=()=>setVisible(sectionVisible.current&&!document.hidden);window.addEventListener('message',receive);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('message',receive);document.removeEventListener('visibilitychange',visibility);};},[]);
 const update=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(s=>({...s,[key]:value}));
 return <Boundary><PlayContext.Provider value={session}><QualityContext.Provider value={presets[effective]}><main tabIndex={-1} data-world-mode={mode} aria-label="BANORI interactive world"><Suspense fallback={<div className="loading"><i/><span>GROWING BANORI WORLD</span></div>}><Canvas shadows frameloop={visible?'always':'never'} dpr={Math.min(devicePixelRatio,presets[effective].dpr)} camera={{position:[46,40,55],fov:38,near:.1,far:260}} gl={{antialias:true,powerPreference:'high-performance'}}><QualityMonitor auto={quality==='auto'} tier={effective} onTier={setTier}/><World settings={settings}/></Canvas></Suspense>
 <aside className={'world-tools '+(mode!=='explore'?'tools-hidden':'')} inert={mode!=='explore'} aria-label="World controls"><span className="tool-label">WORLD CLIMATE</span><div className="button-row"><button aria-pressed={!settings.night} onClick={()=>update('night',false)}>Day</button><button aria-pressed={settings.night} onClick={()=>update('night',true)}>Night</button></div><div className="button-row">{(['clear','rain','snow'] as Weather[]).map(w=><button key={w} aria-pressed={settings.weather===w} onClick={()=>setSettings(s=>({...s,weather:w,paused:w==='clear'?s.paused:false}))}>{w==='clear'?'Sun':w}</button>)}</div><label>Season<select value={settings.season} onChange={e=>update('season',e.target.value as Season)}><option value="summer">Summer</option><option value="autumn">Autumn</option><option value="winter">Winter</option></select></label><label>Explore<select value={settings.destination} onChange={e=>update('destination',e.target.value as Destination)}><option value="overview">Whole world</option><option value="hero">Golden guardian</option><option value="camp">Explorer camp</option><option value="falls">Waterfall</option><option value="lookout">Ridge lookout</option><option value="pine">Deer glade</option><option value="meadow">Rabbit meadow</option><option value="river">Lake wildlife</option><option value="hidden">Hidden sanctuary</option><option value="wetland">Wetland</option><optgroup label="View the island"><option value="top">Top</option><option value="front">Front</option><option value="rear">Rear</option><option value="left">Left</option><option value="right">Right</option><option value="low">Low</option><option value="high">High</option></optgroup></select></label><label>Quality<select value={quality} onChange={e=>setQuality(e.target.value as Quality)}>{['auto','low','medium','high'].map(q=><option key={q} value={q}>{q[0].toUpperCase()+q.slice(1)}</option>)}</select></label><button className="motion-button" aria-pressed={settings.paused} onClick={()=>update('paused',!settings.paused)}>{settings.paused?'Resume motion':'Pause motion'}</button><button className="enter-world" disabled={!asset} onClick={enter}>{asset?'ENTER WORLD':assetStatus==='preparing'?'PREPARING…':'CHARACTER UNAVAILABLE'}</button><span className="tool-help">DRAG TO ORBIT · PINCH TO ZOOM</span></aside><button className="sound-toggle" aria-pressed={audio.enabled} onClick={audio.toggle}>{audio.enabled?'ÂM THANH: BẬT':'BẬT ÂM THANH'}</button><output id="audio-health" hidden data-enabled={audio.enabled} data-level={audio.level.toFixed(6)} data-error={audio.error}/><output id="world-health" hidden aria-hidden="true"/><output id="player-health" hidden aria-hidden="true"/><PlayHUD exit={exit}/></main></QualityContext.Provider></PlayContext.Provider></Boundary>;
}
