import { useQuality } from '../environment/quality';
import { useEffect,useMemo,useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { BufferGeometry,Float32BufferAttribute,Group,Matrix4,PlaneGeometry,Points,ShaderMaterial,Vector2 } from 'three';
import { Reflector } from 'three/examples/jsm/objects/Reflector.js';
import { Refractor } from 'three/examples/jsm/objects/Refractor.js';
import { GRID,heightAt,insideIsland,inSource,isWater,isLake,nearestWaterway,waterLevel,waterwayPoint } from '../world/map';
import type { Settings } from '../environment/settings';
function surface(level:number,source=false){const g=new BufferGeometry(),p:number[]=[],depth:number[]=[],flow:number[]=[];
 const add=(v:Vector2)=>{p.push(v.x,level,v.y);depth.push(Math.max(0,level-heightAt(v.x,v.y)));let nearest=0,best=Infinity,t=0;for(let w=0;w<4;w++){const n=nearestWaterway(v.x,v.y,w);if(n.distance<best){best=n.distance;nearest=w;t=n.t;}}const d=source?new Vector2(0,1):isLake(v.x,v.y)?new Vector2(.82,.31).normalize():waterwayPoint(nearest,Math.min(1,t+.003)).sub(waterwayPoint(nearest,Math.max(0,t-.003))).normalize();flow.push(d.x,d.y);};
 for(let ix=source?-27:-75;ix<(source?-16:75);ix++)for(let iz=source?-46:-59;iz<(source?-35:59);iz++){const x=ix*GRID,z=iz*GRID,a=new Vector2(x,z),b=new Vector2(x+GRID,z),c=new Vector2(x,z+GRID),d=new Vector2(x+GRID,z+GRID);for(const tri of [[a,c,b],[b,c,d]]){const center=tri[0].clone().add(tri[1]).add(tri[2]).multiplyScalar(1/3);if((source&&center.y> -14.4)||!insideIsland(center.x,center.y)||!(source?inSource(center.x,center.y):tri.some(v=>isWater(v.x,v.y)&&!inSource(v.x,v.y))))continue;const poly:Vector2[]=[];for(let i=0;i<3;i++){const v=tri[i],w=tri[(i+1)%3],sv=level-heightAt(v.x,v.y),sw=level-heightAt(w.x,w.y);if(sv>0)poly.push(v);if((sv>0)!==(sw>0))poly.push(v.clone().lerp(w,sv/(sv-sw)));}for(let i=1;i<poly.length-1;i++){add(poly[0]);add(poly[i]);add(poly[i+1]);}}}
 g.setAttribute('position',new Float32BufferAttribute(p,3));g.setAttribute('depth',new Float32BufferAttribute(depth,1));g.setAttribute('flow',new Float32BufferAttribute(flow,2));g.computeVertexNormals();return g;}
const vertex=`attribute float depth;attribute vec2 flow;varying float vDepth;varying vec2 vFlow;varying vec3 world;varying vec4 reflected;varying vec4 refracted;uniform mat4 reflectionMatrix;uniform mat4 refractionMatrix;void main(){world=(modelMatrix*vec4(position,1.0)).xyz;vDepth=depth;vFlow=flow;reflected=reflectionMatrix*vec4(world,1.0);refracted=refractionMatrix*vec4(world,1.0);gl_Position=projectionMatrix*viewMatrix*vec4(world,1.0);}`;
const fragment=`uniform float time;uniform float night;uniform float useTargets;uniform sampler2D reflection;uniform sampler2D refraction;varying float vDepth;varying vec2 vFlow;varying vec3 world;varying vec4 reflected;varying vec4 refracted;void main(){vec2 side=vec2(-vFlow.y,vFlow.x);float along=dot(world.xz,vFlow),across=dot(world.xz,side);float a=sin(along*5.0-time*1.4+sin(across*4.0))*.025;float b=cos(across*7.0+along*2.0-time*.8)*.018;vec3 normal=normalize(vec3(a,1.0,b));vec3 eye=normalize(cameraPosition-world);float fresnel=.035+.24*pow(1.0-max(0.0,dot(eye,normal)),5.0);vec3 shallow=vec3(.27,.687,.64),deep=vec3(.032,.212,.29),main=vec3(.09,.474,.5);vec3 tint=mix(shallow,main,smoothstep(.01,.10,vDepth));tint=mix(tint,deep,smoothstep(.09,.2,vDepth)*.65);vec2 ripple=vec2(a,b)*.035;vec3 refr=texture2D(refraction,refracted.xy/refracted.w+ripple).rgb;vec3 refl=texture2D(reflection,reflected.xy/reflected.w+ripple).rgb;tint=mix(tint,refr,.19*useTargets);tint=mix(tint,refl,fresnel*useTargets);float highlight=pow(max(0.0,sin(along*6.0-time*1.5+sin(across*7.0)*.35)),18.0)*.075;tint=mix(tint,vec3(.695,.905,.824),highlight);float foam=(1.0-smoothstep(.008,.04,vDepth))*.15;tint=mix(tint,shallow,foam);tint*=mix(1.0,.58,night);gl_FragColor=vec4(tint,smoothstep(.0,.035,vDepth)*.81);\n#include <tonemapping_fragment>
#include <colorspace_fragment>}`;
export function Water({settings}:{settings:Settings}){const quality=useQuality();const group=useRef<Group>(null!),frame=useRef(0);const data=useMemo(()=>{const geometry=surface(waterLevel),source=surface(2.8,true),plane=new PlaneGeometry(70,55),size=Math.max(64,quality.water),reflector=new Reflector(plane,{textureWidth:size,textureHeight:size,multisample:0,clipBias:.003}),refractor=new Refractor(plane,{textureWidth:size,textureHeight:size,multisample:0,clipBias:.003});for(const o of [reflector,refractor]){o.position.y=waterLevel;o.rotation.x=-Math.PI/2;o.updateMatrixWorld(true);}const material=new ShaderMaterial({uniforms:{time:{value:0},night:{value:0},useTargets:{value:0},reflection:{value:reflector.getRenderTarget().texture},refraction:{value:refractor.getRenderTarget().texture},reflectionMatrix:{value:new Matrix4()},refractionMatrix:{value:new Matrix4()}},vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false});const sourceMaterial=new ShaderMaterial({uniforms:{...material.uniforms,time:{value:0},useTargets:{value:0}},vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false});return{geometry,source,plane,reflector,refractor,material,sourceMaterial};},[quality.water]);
 useEffect(()=>()=>{data.geometry.dispose();data.source.dispose();data.plane.dispose();data.reflector.dispose();data.refractor.dispose();data.material.dispose();data.sourceMaterial.dispose();},[data]);
 useFrame(({gl,scene,camera},delta)=>{const {material,sourceMaterial,reflector,refractor}=data;for(const m of [material,sourceMaterial]){if(!settings.paused)m.uniforms.time.value+=Math.min(delta,.06);m.uniforms.night.value=settings.night?1:0;}
 // All flat water shares two clipped offscreen passes, throttled to conserve integrated graphics.
 material.uniforms.useTargets.value=quality.water?material.uniforms.useTargets.value:0;
 if(quality.water&&frame.current++%(quality.water<512?12:6)===0){group.current.userData.mainCalls=gl.info.render.calls;group.current.userData.mainTriangles=gl.info.render.triangles;const oldShadow=gl.shadowMap.autoUpdate;gl.shadowMap.autoUpdate=false;group.current.visible=false;reflector.onBeforeRender(gl,scene,camera,reflector.geometry,reflector.material as ShaderMaterial,null!);refractor.onBeforeRender(gl,scene,camera,refractor.geometry,refractor.material as ShaderMaterial,null!);group.current.visible=true;gl.shadowMap.autoUpdate=oldShadow;const inverse=new Matrix4().copy(reflector.matrixWorld).invert();material.uniforms.reflectionMatrix.value.copy((reflector.material as ShaderMaterial).uniforms.textureMatrix.value).multiply(inverse);material.uniforms.refractionMatrix.value.copy((refractor.material as ShaderMaterial).uniforms.textureMatrix.value).multiply(inverse);material.uniforms.useTargets.value=1;}
 },-1);
 return <group ref={group} name="world-water"><mesh geometry={data.geometry} material={data.material}/><mesh geometry={data.source} material={data.sourceMaterial}/><Waterfall settings={settings}/></group>;}
function Waterfall({settings}:{settings:Settings}){const particles=useRef<Points>(null!),clock=useRef(0),mat=useMemo(()=>new ShaderMaterial({uniforms:{time:{value:0}},transparent:true,depthWrite:false,side:2,vertexShader:`varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform float time;varying vec2 v;void main(){float streams=pow(.5+.5*sin(v.x*73.0+sin(v.y*12.0+time*3.0)),5.0);float foam=pow(.5+.5*sin(v.y*70.0+time*11.0+v.x*15.0),9.0);vec3 c=mix(vec3(.36,.71,.74),vec3(.87,.97,.92),streams*.5+foam*.4);gl_FragColor=vec4(c,.75+.2*streams);}`}),[]),array=useMemo(()=>new Float32Array(90*3),[]);useEffect(()=>()=>mat.dispose(),[mat]);useFrame((_,d)=>{if(!settings.paused){clock.current+=Math.min(d,.05);mat.uniforms.time.value=clock.current;}const t=clock.current,a=particles.current.geometry.attributes.position;for(let i=0;i<a.count;i++){const phase=(t*.52+i*.137)%1,angle=i*2.4;a.setXYZ(i,-8.4+Math.cos(angle)*phase*.95,.18+Math.sin(phase*Math.PI)*(.3+i%4*.11),-13.94+Math.sin(angle)*phase*.55);}a.needsUpdate=true;});return <group><mesh position={[-8.5,1.48,-14.175]} rotation={[-.169,0,0]} material={mat}><planeGeometry args={[1.3,2.678,8,20]}/></mesh>{[-.46,.47].map((x,i)=><mesh key={i} position={[-8.5+x,1.48,-14.14+i*.012]} rotation={[-.169,0,0]} material={mat}><planeGeometry args={[.16,2.678,1,12]}/></mesh>)}<mesh position={[-8.5,.19,-13.94]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.75,24]}/><meshBasicMaterial color="#dbf0e5" transparent opacity={.38} depthWrite={false}/></mesh><points ref={particles} frustumCulled={false}><bufferGeometry><bufferAttribute attach="attributes-position" args={[array,3]}/></bufferGeometry><pointsMaterial size={.12} color="#e4f4e9" transparent opacity={.42} depthWrite={false}/></points></group>;}
